version: 2.1

executors:
  default-executor:
    machine: true

jobs:
  generate-and-compress:
    executor: default-executor
    steps:
      - run:
          name: Install pigz
          command: sudo apt-get update && sudo apt-get install -y pigz
      - run:
          name: Generate 10GB file
          command: dd if=/dev/urandom of=./10GBfile.txt bs=1048576 count=10240
      - run: ls -la
      - persist_to_workspace:
          root: ./
          paths:
            - .

  next-job:
    executor: default-executor
    steps:
      - run:
          name: Install pigz
          command: sudo apt-get update && sudo apt-get install -y pigz
      - run:
          name: Switch pgiz
          command: |
              sudo ln -s /usr/bin/pigz /usr/local/bin/gzip
              sudo ln -s /usr/bin/unpigz /usr/local/bin/gunzip
      - attach_workspace:
          at: ./
      - run: ls -la
      - run:
          name: Process compressed file
          command: echo "Processing 5GBfile.txt.gz"

  next-job-nopigz:
    executor: default-executor
    steps:
      - attach_workspace:
          at: ./
      - run: ls -la
      - run:
          name: Process compressed file
          command: echo "Processing 5GBfile.txt.gz"

workflows:
  version: 2
  generate-process:
    jobs:
      - generate-and-compress
      - next-job:
          requires:
            - generate-and-compress
      - next-job-nopigz:
          requires:
            - generate-and-compress
