version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/base:stable

jobs:
  generate-and-compress:
    executor: default-executor
    steps:
      - run:
          name: Install pigz
          command: sudo apt-get update && sudo apt-get install -y pigz
      - run:
          name: Generate 30GB file
          command: dd if=/dev/urandom of=./30GBfile.txt bs=1024 count=31457280
      - run:
          name: Compress 30GB file
          command: pigz 30GBfile.txt
      - run: ls -la
      - persist_to_workspace:
          root: ./
          paths:
            - .

  next-job:
    executor: default-executor
    steps:
      - attach_workspace:
          at: ./
      - run: ls -la
      - run:
          name: Process compressed file
          command: echo "Processing 30GBfile.txt.gz"

workflows:
  version: 2
  generate-process:
    jobs:
      - generate-and-compress
      - next-job:
          requires:
            - generate-and-compress
